#Ler teclado, mostrar tipo primitivo e todas as informações possiveis

x = input('Digite algo: ')
print('{} eh do tipo {}'.format(x, type(x)))
print('{} isalnum: {}'.format(x, x.isalnum()))
print('{} isalpha: {}'.format(x, x.isalpha()))
#print('{} isascii: {}'.format(x, x.isascii()))
print('{} isdecimal: {}'.format(x, x.isdecimal()))
print('{} isdigit: {}'.format(x, x.isdigit()))
print('{} isidentifier: {}'.format(x, x.isidentifier()))
print('{} islower: {}'.format(x, x.islower()))
print('{} isnumeric: {}'.format(x, x.isnumeric()))
print('{} isprintable: {}'.format(x, x.isprintable()))
print('{} isspace: {}'.format(x, x.isspace()))
print('{} istitle: {}'.format(x, x.istitle()))
print('{} isupper: {}'.format(x, x.isupper()))
